app_id: your_app_id
app_secret: your_app_secret
username: your_username
password: your_password
station_name: name_of_your_station
module_name: name_of_your_outdoor_module
module2_name: name_of_additional_indoor_module
interval: 60s
